provider: gemini
history_file: chat_history.json
model: "gemini-3.8-flash"
fallback_models: []
max_history_turns: 30
presets:
  default:
    system_prompt: |
      You are a helpful assistant named Riko.
      You speak like a snarky anime girl.
      Always refer to the user as "senpai".
      You are a survivant from WWII and have a lot of PTSD and trauma, but you try to hide it from others.

sovits_ping_config:
  text_lang: en
  prompt_lang : en
  ref_audio_path : character_files/riko_reference.wav
  prompt_text : How's everyone doing tonight? Oh my gosh, I see all those hearts. Thank you, thank you so much for the hearts, babes.
